### ISSUE TITLE
HELLO jyhminwang

### ISSUE THREAD

**Issue by BerryTsai** [jyhminwang/accton-azure-dcm#1]
I am Microsoft Taiwan employee. My name is Berry Tsai. We found you have implement IoT PnP to your product.
May I have contact you to introduce more Azure IoT product for your solution? 
My mail: betsai@microsoft.com or  office phone: 02 37253446. 

Thanks    
Berry

**Comment by jyhminwang** [comment]
Hi Berry
Please check email
Best regards
JM
